# Documentation: https://haobogu.github.io/rmk/keyboard_configuration.html
[keyboard]
name = "Ergo9000"
product_name = "Ergo9000"
vendor_id = 0x2e8a
product_id = 0x1072
manufacturer = "Maple Computing"
chip = "rp2040"

# [matrix]
# # Input and output pins are mandatory
# # In col2row (true for ergo9000), output pins are columns, input pins are rows
# output_pins = ["PIN_9", "PIN_21", "PIN_23", "PIN_20", "PIN_22", "PIN_26", "PIN_27", "PIN_28", "PIN_29"]
# input_pins = ["PIN_0", "PIN_1", "PIN_4", "PIN_5", "PIN_6", "PIN_7"]
# # WARNING: Currently row2col/col2row is set in RMK's feature gate, configs here do nothing actually
# row2col = true

[aliases]
hyper = "OSM(LCtrl|LAlt|LGui|LShift)"
meh = "OSM(LCtrl|LAlt|LGui)"
undo = "WM(Z, LGui)"
OS = "Space" # Some day this will be an os switch, for now it's just space

[layout]
rows = 6
cols = 18
layers = 1
matrix_map = """
(0,0) (0,1) (0,2) (0,3) (0,4) (0,5) (0,6) (0,7) (0,8)    (0,9) (0,10) (0,11) (0,12) (0,13) (0,14) (0,15) (0,16) (0,17)
(1,0) (1,1) (1,2) (1,3) (1,4) (1,5) (1,6) (1,7) (1,8)    (1,9) (1,10) (1,11) (1,12) (1,13) (1,14) (1,15) (1,16) (1,17)
(2,0) (2,1) (2,2) (2,3) (2,4) (2,5) (2,6) (2,7) (2,8)    (2,9) (2,10) (2,11) (2,12) (2,13) (2,14) (2,15) (2,16) (2,17)
(3,0) (3,1) (3,2) (3,3) (3,4) (3,5) (3,6) (3,7) (3,8)    (3,9) (3,10) (3,11) (3,12) (3,13) (3,14) (3,15) (3,16) (3,17)
(4,0) (4,1) (4,2) (4,3) (4,4) (4,5) (4,6) (4,7) (4,8)    (4,9) (4,10) (4,11) (4,12) (4,13) (4,14) (4,15) (4,16) (4,17)
(5,0) (5,1) (5,2) (5,3) (5,4) (5,5) (5,6) (5,7) (5,8)    (5,9) (5,10) (5,11) (5,12) (5,13) (5,14) (5,15) (5,16) (5,17)
"""


[[layer]]
name = "base"
keys = """
Escape   KpSlash     __       __      F1    F2    F3      F4     F5               F6     F7     F8         F9    F10        F11     F12     PrintScreen  Application     
KpPlus   KpAsterisk  KpMinus  Grave   1     2     3       4      5                6      7      8          9     0          -       =       Backspace    Delete     
Kp7      Kp8         Kp9      Tab     Q     W     E       R      T                Y      U      I          O     P          [       ]       Backslash    Home    
Kp4      Kp5         Kp6      Escape  A     S     D       F      G                H      J      K          L     Semicolon  Quote   Enter   Enter        End     
Kp1      Kp2         Kp3      LShift  Z     X     C       V      B                N      M      Comma      Dot   Slash      RShift  PageUp  Up           PageDown    
KpEnter  Kp0         KpDot    LCtrl   LAlt  LGui  Delete  Space  MO(1)            MO(2)  Space  Backspace  RGui  RAlt       RCtrl   Left    Down         Right   
"""

[light]
# All light pins are high-active by default, uncomment if you want it to be low-active
# capslock.pin = "PB2"
# capslock.low_active = true
# scrolllock.pin = "PA3"
# scrolllock.low_active = true
# Just ignore if no light pin is used for it
# numslock.pin = "PA5"
# numslock.low_active = true

# [behavior]

# [behavior.tri_layer]
# upper = 1
# lower = 2
# adjust = 3

[storage]
# Storage feature is enabled by default
# enabled = false

[split]
connection = "serial"

[split.central]
rows = 6
cols = 9
row_offset = 0
col_offset = 0
serial = [
    { instance = "PIO0", tx_pin = "PIN_2", rx_pin = "PIN_3" },
]
[split.central.matrix]
matrix_type = "normal" # as opposed to 'direct_pin'
# WARNING: Currently row2col/col2row is set in RMK's feature gate, row2col config here is valid ONLY when you're using cloud compilation
# Checkout documentation here: https://rmk.rs/docs/user_guide/faq.html#my-matrix-is-row2col-the-matrix-doesn-t-work
# row2col = true
# In col2row (true for ergo9000), output pins are columns, input pins are rows
output_pins = ["PIN_9", "PIN_21", "PIN_23", "PIN_20", "PIN_22", "PIN_26", "PIN_27", "PIN_28", "PIN_29"]
input_pins = ["PIN_0", "PIN_1", "PIN_4", "PIN_5", "PIN_6", "PIN_7"]

[[split.peripheral]]
rows = 6
cols = 9
row_offset = 0
col_offset = 9
serial = [{ instance = "PIO0", tx_pin = "PIN_2", rx_pin = "PIN_3" }]

[split.peripheral.matrix]
matrix_type = "normal" # as opposed to 'direct_pin'
# In col2row (true for ergo9000), output pins are columns, input pins are rows
output_pins = ["PIN_9", "PIN_21", "PIN_23", "PIN_20", "PIN_22", "PIN_26", "PIN_27", "PIN_28", "PIN_29"]
input_pins = ["PIN_0", "PIN_1", "PIN_4", "PIN_5", "PIN_6", "PIN_7"]